#!/usr/bin/env python3
"""Build reviewed Stage 2A HFNU staging from committed canonical raw evidence.

This script is intentionally offline and deterministic. It validates the
archived source text structure, emits HFNU 2026 admission scores, 2024
application statistics, and 2024-2026 syllabus/reference-book staging, and can
compare generated bytes with the committed staging files.
"""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
STAGING_ROOT = ROOT / "staging" / "HFNU"
RAW_ROOT = ROOT / "raw"
SCHEMA_VERSION = "0.3.0"
EXTRACTED_AT = "2026-08-15T04:00:00+00:00"

SCORE_2026 = [
    ("商务英语", "", "342.5", "61.5", None, "236.5", None, 1),
    ("电子信息工程", "", "418", "70", "399", "213", None, 1),
    ("药物制剂", "", "301.5", "51.5", None, "179.5", None, 1),
    ("人力资源管理", "", "453(专业课1:125.5)", "65", None, "378", None, 1),
    ("市场营销", "", "451.5(专业课1:126)", "64", None, "443", None, 1),
    ("网络与新媒体", "", "443", "60", None, "428.5", None, 1),
    ("通信工程", "", "341.5", "69.5", None, "204", None, 1),
    ("化学工程与工艺", "", "208.5", "63.5", None, "222", None, 1),
    ("软件工程", "", "444.5", "63", "309", "363.5", None, 1),
    ("互联网金融", "", "422.5", None, None, "400", None, 1),
    ("学前教育", "师范", "395.5", "53.5", None, "287", None, 1),
    ("生物制药", "", "417", "70.5", None, "266", None, 1),
    ("经济统计学", "", "378", "57(素质39)", None, "362", None, 1),
    ("新能源材料与器件", "", "367", "60.5", None, "339.5", None, 2),
    ("音乐学", "师范", "430", None, None, None, None, 2),
    ("视觉传达设计", "", "440", "80", None, "409.66", None, 2),
    ("服装与服饰设计", "", "396.33", None, None, "362", None, 2),
    ("动画", "", "429.66", "80.5", None, "424.33", None, 2),
    ("运动康复", "", "400.5", "72", None, "391.5", None, 2),
    ("财务管理", "与安徽工业经济职业技术学院联合培养", "442(专业课1:133)", "74.5", None, "252.5", None, 2),
    ("电气工程及其自动化", "与安徽工业经济职业技术学院联合培养", "409.5", "74.5", None, "302.5", None, 2),
    ("网络工程", "与安徽工业经济职业技术学院联合培养", "467.5", "75", None, "409.5", None, 2),
    ("计算机科学与技术", "与安徽工业经济职业技术学院联合培养", "437", "63", None, "407", None, 2),
    ("小学教育", "师范；与淮北职业技术学院联合培养", "448(专业课1:118.5)", "57.5", None, "446", None, 2),
    ("电气工程及其自动化", "与淮北职业技术学院联合培养", "455(专业课1:142)", None, None, "249.5", None, 2),
    ("环境设计", "与马鞍山师范高等专科学校联合培养", "407.66", "72.5", None, "408.66", None, 2),
    ("计算机科学与技术", "与马鞍山师范高等专科学校联合培养", "405", "61", None, "262", None, 2),
    ("食品质量与安全", "与马鞍山师范高等专科学校联合培养", "245.5(专业课1:73)", "50.5", None, "226.5", None, 2),
]

SUBJECT_ALIASES = {
    "康复评定": "康复功能评定学",
}
HEADING_ALIASES = {
    "运动解剖生理学": ("运动解剖生理学", "运动解剖学"),
    "康复功能评定学": ("康复功能评定学", "康复评定"),
    "C语言程序设计": ("C语言程序设计", "C 语言程序设计"),
}
BOOK_TITLE_HINTS = (
    "室内设计手绘技法与快题表现",
    "中国音乐史与名作赏析",
    "新编数据结构习题与解析",
    "商务英语综合教程1",
    "数字电子技术基础",
    "康复功能评定学",
    "无机化学简明教程",
    "无机及分析化学",
    "生物化学简明教程",
    "微生物学教程",
    "运动解剖生理学",
    "运动解剖学",
    "运动生理学",
    "传播学概论",
    "新闻学概论",
    "酒店管理概论",
    "C语言程序设计",
    "自动控制原理与系统",
    "自动控制原理",
    "电路分析基础",
    "经济统计学",
    "普通物理学",
    "和声学教程",
    "教育学原理",
    "管理学原理",
    "基础会计",
    "西方经济学",
    "导游业务",
    "建筑速写",
    "插画设计",
    "色彩表现",
    "中国音乐史",
    "数据结构",
    "心理学",
    "速写",
    "电路",
)
BOOK_RULES = {
    "教育学": ("教育学原理",),
    "心理学": ("心理学",),
    "管理学原理": ("管理学原理",),
    "会计学原理": ("基础会计",),
    "微观经济学": ("西方经济学",),
    "传播学概论": ("传播学概论",),
    "新闻学概论": ("新闻学概论",),
    "综合商务英语": ("商务英语综合教程",),
    "旅游与酒店管理": ("导游业务", "酒店管理概论"),
    "人物速写": ("速写",),
    "插画设计": ("插画设计", "色彩表现"),
    "建筑速写": ("建筑速写",),
    "室内设计表现": ("室内设计手绘技法", "色彩表现"),
    "和声": ("和声学教程",),
    "中国音乐史": ("中国音乐史",),
    "运动解剖生理学": ("运动解剖生理学", "运动解剖学", "运动生理学"),
    "康复功能评定学": ("康复功能评定学",),
    "基础无机化学": ("无机及分析化学",),
    "基础分析化学": ("无机及分析化学",),
    "无机化学": ("无机化学简明教程",),
    "大学物理": ("普通物理学",),
    "统计学": ("经济统计学",),
    "电路分析基础": ("电路",),
    "数字电子技术基础": ("数字电子技术基础",),
    "自动控制原理": ("自动控制原理",),
    "C语言程序设计": ("C语言程序设计",),
    "数据结构": ("数据结构", "新编数据结构习题与解析"),
    "生物化学": ("生物化学简明教程",),
    "微生物学": ("微生物学教程",),
}


class StagingError(RuntimeError):
    pass


@dataclass
class Section:
    majors: list[str]
    subjects: list[str]
    header: str
    segment: str
    absolute_start: int
    absolute_end: int
    full_text: str


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def dump_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")


def normalize_compact(value: str) -> str:
    return re.sub(r"\s+", "", value).replace("（", "(").replace("）", ")")


def normalize_subject(value: str) -> str:
    compact = normalize_compact(value)
    return SUBJECT_ALIASES.get(compact, compact)


def page_number(text: str, absolute_position: int) -> int:
    return text.count("\f", 0, absolute_position) + 1


def page_value(text: str, start: int, end: int) -> int | str:
    first = page_number(text, start)
    last = page_number(text, max(start, end - 1))
    return first if first == last else f"{first}-{last}"


def parse_sections(year: int) -> tuple[str, list[Section]]:
    path = RAW_ROOT / str(year) / "HFNU" / f"DOC-HFNU-{year}-DG.txt"
    text = path.read_text(encoding="utf-8-sig")
    starts = [match.start() for match in re.finditer("【考试科目】", text)]
    header_starts = [text.rfind("\f", 0, start) + 1 for start in starts]
    sections: list[Section] = []
    for index, start in enumerate(starts):
        header_start = header_starts[index]
        end = header_starts[index + 1] if index + 1 < len(starts) else len(text)
        header_lines = []
        for raw in text[header_start:start].splitlines():
            line = raw.strip()
            if not line or re.fullmatch(r"\d+", line):
                continue
            header_lines.append(line)
        header = normalize_compact("".join(header_lines))
        if not header.endswith("专业"):
            raise StagingError(f"cannot parse DG section header for {year}: {header!r}")
        majors = [item for item in header[:-2].split("、") if item]
        segment = text[start:end]
        if "【考试范围】" not in segment:
            raise StagingError(f"DG section has no exam range: {year} {header}")
        exam_block = segment.split("【考试范围】", 1)[0]
        subjects = [normalize_subject(item) for item in re.findall(r"《([^》]+)》", exam_block)]
        if len(subjects) != 2:
            raise StagingError(f"DG section must have two subjects: {year} {header}: {subjects}")
        sections.append(Section(majors, subjects, header, segment, start, end, text))
    return text, sections


def find_heading(body: str, subject: str) -> int | None:
    variants = HEADING_ALIASES.get(subject, (subject,))
    for variant in variants:
        pattern = r"《\s*" + r"\s*".join(re.escape(char) for char in variant) + r"\s*》"
        match = re.search(pattern, body)
        if match:
            return match.start()
    for variant in variants:
        match = re.search(re.escape(variant), body)
        if match:
            return match.start()
    return None


def subject_raw_text(section: Section, subject_index: int) -> tuple[str, int, int]:
    marker = section.segment.index("【考试范围】") + len("【考试范围】")
    body = section.segment[marker:]
    starts = [find_heading(body, subject) for subject in section.subjects]
    if starts[0] is None:
        starts[0] = 0
    if starts[1] is None or int(starts[1]) - int(starts[0]) < 80:
        local_start = 0
        local_end = len(body)
    elif subject_index == 0:
        local_start = int(starts[0])
        local_end = int(starts[1])
    else:
        local_start = int(starts[1])
        local_end = len(body)
    raw = body[local_start:local_end].strip()
    if len(raw) < 40:
        raw = body.strip()
        local_start = 0
        local_end = len(body)
    absolute_start = section.absolute_start + marker + local_start
    absolute_end = section.absolute_start + marker + local_end
    return raw, absolute_start, absolute_end


def reference_entries(section: Section) -> list[tuple[str, int]]:
    results: list[tuple[str, int]] = []
    marker_matches = list(re.finditer("【参考书目】", section.segment))
    exact_subjects = {normalize_compact(f"《{item}》") for item in section.subjects}
    for marker_index, marker in enumerate(marker_matches):
        region_start = marker.end()
        region_end = marker_matches[marker_index + 1].start() if marker_index + 1 < len(marker_matches) else len(section.segment)
        region = section.segment[region_start:region_end]
        current: list[str] = []
        current_position: int | None = None
        offset = 0
        for raw_line in region.splitlines(keepends=True):
            stripped = raw_line.replace("\f", "").strip()
            line_position = section.absolute_start + region_start + offset
            offset += len(raw_line)
            if not stripped or re.fullmatch(r"\d+", stripped):
                continue
            if normalize_compact(stripped) in exact_subjects:
                break
            if re.match(r"^\d+[.、．]", stripped):
                if current:
                    results.append((" ".join(current), int(current_position)))
                current = [re.sub(r"^\d+[.、．]\s*", "", stripped)]
                current_position = line_position
                continue
            if current:
                current.append(stripped)
                continue
            if "出版社" in stripped or "ISBN" in stripped or "《" in stripped or stripped.startswith("http"):
                current = [stripped]
                current_position = line_position
                continue
            if re.match(r"^(第[一二三四五六七八九十]+章|考核要点|考试时间|考试内容)", stripped):
                break
        if current:
            results.append((" ".join(current), int(current_position)))
    deduped: list[tuple[str, int]] = []
    seen: set[str] = set()
    for entry, position in results:
        key = normalize_compact(entry)
        if key not in seen:
            seen.add(key)
            deduped.append((entry, position))
    return deduped


def book_title(entry: str) -> str:
    matches = re.findall(r"《([^》]+)》", entry)
    if matches:
        title = matches[0].rstrip("》").strip()
        if not re.fullmatch(r"[\d.。]+", title):
            return title
    compact = normalize_compact(entry)
    for hint in sorted(BOOK_TITLE_HINTS, key=len, reverse=True):
        if normalize_compact(hint) in compact:
            return hint
    candidate = re.sub(r"^\d+[.、．]\s*", "", entry).split("，", 1)[0].split(",", 1)[0].strip()
    return candidate


AUTHOR_ROLE_RE = re.compile(r"(编著|主编|教材编写组|编写组|合著|著|编|译)")
GENERIC_AUTHOR_PREFIXES = (
    "马克思主义理论研究和建设工程重点教材",
    "马克思主义理论研究和建设工程",
)


def _flexible_text_pattern(value: str) -> str:
    return r"\s*".join(re.escape(char) for char in value if not char.isspace())


def _clean_author_candidate(value: str) -> str:
    value = re.sub(r"\s+", " ", value).strip(" ，,。.；;:：·")
    value = re.sub(
        r"^[（(]\s*(?:第?\s*[一二三四五六七八九十0-9]+\s*版|马工程)\s*[）)]",
        "",
        value,
    )
    value = value.strip(" ，,。.；;:：·")
    value = re.sub(
        r"^(?:上册|下册|第?\s*[一二三四五六七八九十0-9]+\s*版)\s*[，,。.]*",
        "",
        value,
    )
    value = re.split(
        r"[，,。.]+\s*(?=(?:第?\s*[一二三四五六七八九十0-9]+\s*版|19\d{2}|20\d{2}|北京(?:\s*[:：])?|ISBN\s*[:：]))",
        value,
        maxsplit=1,
    )[0]
    value = re.split(
        r"(?=19\d{2}|20\d{2}|北京(?:\s*[:：])?|ISBN\s*[:：])",
        value,
        maxsplit=1,
    )[0]
    value = re.sub(r"\s+(?=(?:编著|主编|教材编写组|编写组|合著|著|编|译))", "", value)
    return value.strip(" ，,。.；;:：·")


def _is_author_candidate(value: str) -> bool:
    compact = re.sub(r"\s+", "", value)
    if not compact or len(compact) > 60:
        return False
    if any(compact.startswith(prefix) for prefix in GENERIC_AUTHOR_PREFIXES):
        return False
    if compact in {"马工程", "上册", "下册"} or re.fullmatch(
        r"第?[一二三四五六七八九十0-9]+版", compact
    ):
        return False
    if "出版社" in compact or "http" in compact.lower():
        return False
    if AUTHOR_ROLE_RE.search(compact):
        return True
    if re.fullmatch(
        r"[\u4e00-\u9fff·]{2,12}(?:(?:\s+|[、，,])[\u4e00-\u9fff·]{2,12}){0,7}",
        value,
    ):
        return True
    if re.fullmatch(r"[\u4e00-\u9fff]{2,20}大学", compact):
        return True
    return False


def parse_author(entry: str, title: str) -> str:
    """Extract only an explicitly printed author/editor expression.

    The source PDFs use several bibliographic styles and contain visual line
    wrapping.  This parser never looks up or infers a person: it only returns a
    bounded substring adjacent to the printed title when that substring is an
    explicit name list, university, or editorial-role expression.
    """

    normalized = re.sub(r"\s+", " ", entry).strip()
    title_pattern = _flexible_text_pattern(title)
    explicit_group = re.search(
        r"《\s*" + title_pattern + r"\s*》\s*编写组", normalized
    )
    if explicit_group:
        return re.sub(r"\s+", "", explicit_group.group(0))

    match = re.search(r"《\s*" + title_pattern + r"\s*》", normalized)
    if not match:
        match = re.search(title_pattern, normalized)
    if not match:
        return ""

    before = _clean_author_candidate(normalized[: match.start()])
    if _is_author_candidate(before):
        return before

    after = normalized[match.end() :]
    after = re.sub(r"^\s*(?:[（(][^）)]{0,40}[）)]\s*)+", "", after)
    after = re.sub(
        r"^\s*(?:上册|下册|第?\s*[一二三四五六七八九十0-9]+\s*版)\s*",
        "",
        after,
    )
    after = after.lstrip(" ，,。.；;:：·")
    publisher = re.search(r"[\u4e00-\u9fffA-Za-z·\s]+出\s*版\s*社", after)
    if publisher:
        after = after[: publisher.start()]

    candidate = _clean_author_candidate(after)
    if _is_author_candidate(candidate):
        return candidate
    for part in re.split(r"[，,。.]+", after):
        candidate = _clean_author_candidate(part)
        if _is_author_candidate(candidate):
            return candidate
    return ""


def parse_publisher(entry: str) -> str:
    compact = re.sub(r"\s+", "", entry)
    matches = re.findall(r"([\u4e00-\u9fffA-Za-z·]+出版社)", compact)
    return matches[-1] if matches else ""


def parse_edition(entry: str) -> str:
    match = re.search(r"(第\s*[一二三四五六七八九十0-9]+\s*版|[一二三四五六七八九十]+版)", entry)
    return re.sub(r"\s+", "", match.group(1)) if match else ""


def parse_isbn(entry: str) -> str:
    match = re.search(r"ISBN\s*[:：]?\s*([0-9Xx-]+)", entry, re.I)
    return match.group(1) if match else ""


def assigned_subjects(subjects: list[str], title: str, entry: str) -> list[str]:
    compact = normalize_compact(title + " " + entry)
    assigned: list[str] = []
    for subject in subjects:
        rules = BOOK_RULES.get(subject)
        if not rules:
            raise StagingError(f"no book assignment rules for subject: {subject}")
        if any(normalize_compact(rule) in compact for rule in rules):
            assigned.append(subject)
    return assigned


SCORE_TRAINING_INSTITUTIONS = (
    "安徽工业经济职业技术学院",
    "淮北职业技术学院",
    "马鞍山师范高等专科学校",
)


def score_training_institution(notes_raw: str) -> str:
    matches = [name for name in SCORE_TRAINING_INSTITUTIONS if name in notes_raw]
    if len(matches) > 1:
        raise StagingError(f"score note contains multiple training institutions: {notes_raw}")
    return matches[0] if matches else ""


def metadata(year: int, source_id: str, data: list[dict[str, Any]], method: str) -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_VERSION,
        "source_school_id": "HFNU",
        "source_year": str(year),
        "source_document_id": source_id,
        "extraction_method": method,
        "extracted_at": EXTRACTED_AT,
        "data": data,
    }


def admission_scores_payload() -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    for major, notes_raw, normal, exempt, non_exempt, poor, skill, page in SCORE_2026:
        institution = score_training_institution(notes_raw)
        row_key = f"{major}|{institution or '合肥师范学院'}"
        rows.append(
            {
                "major_name_raw": major,
                "notes_raw": notes_raw,
                "score_normal_raw": normal,
                "score_registered_poor_family_raw": poor,
                "score_retired_culture_exam_exempt_raw": exempt,
                "score_retired_non_exempt_raw": non_exempt,
                "score_skill_competition_raw": skill,
                "source_locator": {
                    "asset_id": "ASSET-HFNU-2026-LQ-EMBEDDED-PDF",
                    "page": page,
                    "table": 1,
                    "row_key": row_key,
                },
            }
        )
    return metadata(2026, "SRC-HFNU-2026-LQ", rows, "manual_verified_from_official_pdf_table")


def application_statistics_payload() -> dict[str, Any]:
    path = RAW_ROOT / "2024" / "HFNU" / "DOC-HFNU-2024-BMRS_parsed.txt"
    lines = [line.strip() for line in path.read_text(encoding="utf-8-sig").splitlines() if line.strip()]
    try:
        start = lines.index("序号")
        end = next(index for index, line in enumerate(lines[start:], start) if line.startswith("上一篇："))
    except (ValueError, StopIteration) as exc:
        raise StagingError("cannot locate 2024 BMRS table") from exc
    cells = lines[start:end]
    if cells[:4] != ["序号", "专业名称", "计划数", "报考人数"]:
        raise StagingError(f"unexpected BMRS header: {cells[:4]}")
    rows: list[dict[str, Any]] = []
    for offset in range(4, len(cells), 4):
        chunk = cells[offset : offset + 4]
        if len(chunk) != 4:
            raise StagingError(f"incomplete BMRS row: {chunk}")
        sequence, raw_major, plan, applicants = chunk
        if not sequence.isdigit() or not plan.isdigit() or not applicants.isdigit():
            raise StagingError(f"invalid BMRS row: {chunk}")
        match = re.match(r"^(.*?)[（(]([^()（）]+)[）)]$", raw_major)
        major = match.group(1).strip() if match else raw_major
        institution = match.group(2).strip() if match else ""
        row_key = f"{major}|{institution or '合肥师范学院'}"
        rows.append(
            {
                "major_name_raw": major,
                "training_institution_name_raw": institution,
                "plan_count_raw": int(plan),
                "applicant_count_raw": int(applicants),
                "qualified_count_raw": None,
                "admitted_count_raw": None,
                "source_locator": {
                    "asset_id": "ASSET-HFNU-2024-BMRS-HTML",
                    "table": 1,
                    "row": int(sequence),
                    "row_key": row_key,
                },
            }
        )
    if len(rows) != 30:
        raise StagingError(f"expected 30 BMRS rows, found {len(rows)}")
    return metadata(2024, "SRC-HFNU-2024-BMRS", rows, "deterministic_parse_of_reviewed_official_html_text")


def syllabus_and_books_payloads(year: int) -> tuple[dict[str, Any], dict[str, Any]]:
    full_text, sections = parse_sections(year)
    exam_rows = load_json(STAGING_ROOT / str(year) / "exam_subjects.json")["data"]
    section_by_major: dict[str, Section] = {}
    for section in sections:
        for major in section.majors:
            if major in section_by_major:
                raise StagingError(f"duplicate DG major section: {year} {major}")
            section_by_major[major] = section
    expected_majors = {str(row["major_name_raw"]) for row in exam_rows}
    if set(section_by_major) != expected_majors:
        raise StagingError(
            f"DG major coverage differs from exam staging for {year}: "
            f"missing={sorted(expected_majors-set(section_by_major))}, "
            f"extra={sorted(set(section_by_major)-expected_majors)}"
        )

    syllabus_rows: list[dict[str, Any]] = []
    book_rows: list[dict[str, Any]] = []
    pdf_asset_id = f"ASSET-HFNU-{year}-DG-PDF"
    for exam_row in exam_rows:
        major = str(exam_row["major_name_raw"])
        subjects = [normalize_subject(str(exam_row["professional_subject_1"])), normalize_subject(str(exam_row["professional_subject_2"]))]
        section = section_by_major[major]
        if section.subjects != subjects:
            raise StagingError(f"DG subject pair mismatch: {year} {major}: {section.subjects} != {subjects}")

        entries = reference_entries(section)
        parsed_books: list[dict[str, Any]] = []
        for entry, absolute_position in entries:
            title = book_title(entry).strip()
            if not title or re.fullmatch(r"[\d.。]+", title) or len(normalize_compact(title)) < 2:
                continue
            assigned = assigned_subjects(subjects, title, entry)
            if not assigned:
                continue
            for subject in assigned:
                parsed_books.append(
                    {
                        "subject": subject,
                        "book_name_raw": title,
                        "author_raw": parse_author(entry, title),
                        "publisher_raw": parse_publisher(entry),
                        "edition_raw": parse_edition(entry),
                        "isbn_raw": parse_isbn(entry),
                        "entry_raw": entry,
                        "reference_key_raw": normalize_compact(entry),
                        "page": page_number(full_text, absolute_position),
                    }
                )
        for subject in subjects:
            if not any(item["subject"] == subject for item in parsed_books):
                raise StagingError(f"no reference book mapped: {year} {major} {subject}")

        for subject_index, subject in enumerate(subjects):
            raw_text, absolute_start, absolute_end = subject_raw_text(section, subject_index)
            locator = {
                "asset_id": pdf_asset_id,
                "page": page_value(full_text, absolute_start, absolute_end),
                "section": subject,
                "row_key": f"{major}|{subject}",
            }
            syllabus_rows.append(
                {
                    "major_name_raw": major,
                    "subject_name_raw": subject,
                    "title_raw": f"《{subject}》考试大纲",
                    "raw_text": raw_text,
                    "source_locator": locator,
                }
            )
            seen_books: set[str] = set()
            for book in parsed_books:
                if book["subject"] != subject:
                    continue
                key = book["reference_key_raw"]
                if key in seen_books:
                    continue
                seen_books.add(key)
                book_rows.append(
                    {
                        "major_name_raw": major,
                        "subject_name_raw": subject,
                        "book_name_raw": book["book_name_raw"],
                        "author_raw": book["author_raw"],
                        "publisher_raw": book["publisher_raw"],
                        "edition_raw": book["edition_raw"],
                        "isbn_raw": book["isbn_raw"],
                        "entry_raw": book["entry_raw"],
                        "reference_key_raw": book["reference_key_raw"],
                        "source_locator": {
                            "asset_id": pdf_asset_id,
                            "page": book["page"],
                            "section": "参考书目",
                            "row_key": f"{major}|{subject}|{book['book_name_raw']}",
                        },
                    }
                )

    syllabus_rows.sort(key=lambda row: (row["major_name_raw"], row["subject_name_raw"]))
    book_rows.sort(key=lambda row: (row["major_name_raw"], row["subject_name_raw"], row["book_name_raw"], row["reference_key_raw"]))
    return (
        metadata(year, f"SRC-HFNU-{year}-DG", syllabus_rows, "deterministic_parse_of_reviewed_official_pdf_text"),
        metadata(year, f"SRC-HFNU-{year}-DG", book_rows, "deterministic_parse_of_reviewed_official_pdf_text"),
    )


def expected_files() -> dict[Path, bytes]:
    files: dict[Path, bytes] = {
        STAGING_ROOT / "2026" / "admission_scores.json": dump_bytes(admission_scores_payload()),
        STAGING_ROOT / "2024" / "application_statistics.json": dump_bytes(application_statistics_payload()),
    }
    for year in (2024, 2025, 2026):
        syllabus, books = syllabus_and_books_payloads(year)
        files[STAGING_ROOT / str(year) / "syllabus.json"] = dump_bytes(syllabus)
        files[STAGING_ROOT / str(year) / "reference_books.json"] = dump_bytes(books)
    return files


def apply() -> int:
    files = expected_files()
    for path, data in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    print(f"Stage 2A HFNU staging: PASS ({len(files)} files written)")
    return 0


def check() -> int:
    errors: list[str] = []
    files = expected_files()
    for path, expected in files.items():
        if not path.is_file():
            errors.append(f"missing staging file: {path.relative_to(ROOT)}")
        elif path.read_bytes() != expected:
            errors.append(f"staging bytes differ from deterministic extraction: {path.relative_to(ROOT)}")
    if errors:
        print("Stage 2A HFNU staging check: FAIL")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"Stage 2A HFNU staging check: PASS ({len(files)} files)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--apply", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        return apply() if args.apply else check()
    except (StagingError, OSError, json.JSONDecodeError, KeyError, ValueError) as exc:
        print(f"Stage 2A HFNU staging: FAIL\n- {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
